remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Documentación

nombres: Fredy Posada Alberto Yarce
submodulo: moviles 1
periodo: 2023-2
url_foto: https://firebasestorage.googleapis.com/v0/b/evidencias-28045.appspot.com/o/foto.png?alt=media&token=8c8fcddf-0869-46a7-8aa9-4ebd0cce1733
